databases:
  - name: spottafy
    user: spottafy
    plan: free
    region: ohio

services:
  - type: web
    name: spottafy
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spottafy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false